packages:
  - "packages/*"
  - "devtools/*"
ignoredBuiltDependencies:
  - keccak
  - bufferutil
  - utf-8-validate
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - secp256k1
# bufferutil and utf-8-validate are optional native WS performance addons; omitting
# them here skips their node-gyp compile and uses the pure-JS fallback instead.
# This avoids ARM64 build failures since prebuilt binaries are unavailable.
